# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
variables:
  acrname: acr03012024
  imagetag: $(Build.BuildId)

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        containerRegistry: 'ADO-ACR-Connect'
        repository: 'docker-app-image'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(imagetag)
          latest
    - task: Docker@2
      displayName: push Docker Image to ACR
      inputs:
        containerRegistry: 'ADO-ACR-Connect'
        repository: 'docker-app-image'
        command: 'push'
        tags: |
          $(imagetag)
          latest
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(System.DefaultWorkingDirectory)/docker-app
        Contents: |
          app.yaml
          service.yaml
        TargetFolder: '$(Build.ArtifactStagingDirectory)/menifest'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/menifest'
        artifact: 'k8s-atrifacts'
        publishLocation: 'pipeline'